version: "3.8"
services:
  ec2-monitor:
    build:
      dockerfile: dockerfile
      image: ec2-monitor:latest
    volumes:
      - ./.aws:/root/.aws/
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 20
        